"""Generate RESULTS.md from actual runs. No figure in that file is typed by hand."""
from __future__ import annotations

import datetime as dt
import subprocess

from cassum.ablate import run
from cassum.sim import default_fleet, flat_fleet


def commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def block(r: dict) -> str:
    w, o = r["with_memory"], r["without_memory"]
    ratio = round(o["usdc_per_payload"] / w["usdc_per_payload"], 3) if w["usdc_per_payload"] else None
    return (
        f"### `{r['fleet']}`\n\n"
        f"| | calls | USDC | USDC per delivered payload |\n"
        f"|---|---:|---:|---:|\n"
        f"| with memory | {w['calls']} | {w['usdc']} | {w['usdc_per_payload']} |\n"
        f"| memory deleted | {o['calls']} | {o['usdc']} | {o['usdc_per_payload']} |\n\n"
        f"Both runs delivered {w['delivered']} payloads. "
        f"Difference {r['usdc_saved']} USDC ({r['pct_saved']}%), "
        f"a {ratio}x ratio in cost per payload.\n"
    )


def main() -> None:
    lines = [
        "# Results",
        "",
        f"Generated by `tools/report.py` at {dt.datetime.now(dt.timezone.utc).isoformat()} "
        f"from commit `{commit()}`. Every number below is computed from a run, not typed.",
        "",
        "## The deletion test",
        "",
        "Same workload twice: once against Sibyl Memory, once against a `NullStore`",
        "that accepts every write and returns nothing on every read. That second run",
        "is literally the judges' litmus test, executed rather than asserted.",
        "",
        "**What the memoryless agent does, stated plainly:** it buys from the",
        "cheapest provider by sticker price, every time. That is not a strawman, it",
        "is the only rational policy available with no purchase history. The result",
        "below is the cost of that being the only available signal.",
        "",
    ]
    for f in (default_fleet, flat_fleet):
        lines.append(block(run(fleet=f)))
    lines += [
        "## What a LIVE run can and cannot show",
        "",
        "The simulated comparison above is the savings claim. A live run against",
        "`x402.ochinimus.app` **cannot** produce a second one, and must never be",
        "read as corroborating it.",
        "",
        "**The payee is our own treasury.** `payTo` on both rails is an address",
        "this project controls, so USDC paid in a live run returns to the same",
        "hands. A \"saving\" measured against that is money moved from one pocket",
        "to another, and any percentage computed from it is circular.",
        "",
        "A live run has two narrower jobs, and only these two:",
        "",
        "1. **Prove settlement works** — one verifiable transaction hash for a",
        "   real x402 payment, on chain, that anyone can look up.",
        "2. **Record real empty rates** — how often each sampled endpoint",
        "   actually returns something usable, measured rather than simulated.",
        "",
        "Those go in the provider records like any other purchase. What does NOT",
        "follow from them is a cost-per-payload figure, because the cost side is",
        "not arm's length. The dispersion in `default_fleet` is chosen; the",
        "dispersion in a live fleet would be real but the prices would not be.",
        "",
        "## Reading these together",
        "",
        "`default_fleet` has real dispersion: hollow-cheap is cheapest per call and",
        "dearest per payload, steady-dear is the reverse. Memory finds that and the",
        "spend falls by half.",
        "",
        "`flat_fleet` has none: every provider costs the same per delivered payload.",
        "Memory finds nothing, pays for the exploration anyway, and ends up more",
        "expensive. This negative is pinned by",
        "`test_memory_is_overhead_when_no_provider_has_an_edge` and is kept on",
        "purpose. **Memory pays when providers differ in cost per delivered payload,",
        "and costs when they do not.**",
        "",
        "## Limits",
        "",
        "These providers are deterministic simulations in `cassum/sim.py`. The",
        "arithmetic is real and reproducible; the failure rates are chosen. Numbers",
        "against live paid endpoints are a separate measurement and are not claimed",
        "here -- and per the section above, a live run against our own treasury",
        "could not produce a comparable one even if it were run.",
        "",
        "Settlement runs on either rail, selected by `CASSUM_RAIL`. Each rail",
        "shells out to a separate JS payer, and this repo contains no signing",
        "code of its own: `solana` uses @seekdaseek/plugin-agentfeed, `base` uses",
        "@seekdaseek/x402-wallet. Both have prior live mainnet settlements. The",
        "default is `solana` so that upgrading this package never silently",
        "changes which chain money moves on.",
        "",
    ]
    out = "\n".join(lines)
    with open("RESULTS.md", "w") as f:
        f.write(out)
    print(out)


if __name__ == "__main__":
    main()
